### ISSUE TITLE
Server error when starting first time

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-skeleton-gateway-site#9]
When starting the Gateway skeleton for the first time I get a server error. This was in the logs:

`[2021-11-27 11:38:14] grav.CRITICAL: syntax error, unexpected end of file, expecting ']' - Trace: #0 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Config/CompiledBase.php(112): Grav\Common\Config\CompiledBase->loadCompiledFile('/home/xxxxxxxx/...') #1 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Service/ConfigServiceProvider.php(172): Grav\Common\Config\CompiledBase->load() #2 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Service/ConfigServiceProvider.php(74): Grav\Common\Service\ConfigServiceProvider::languages(Object(Grav\Common\Grav)) #3 /home/xxxxxxxx/public_html/themes/gateway/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #4 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Themes.php(353): Pimple\Container->offsetGet('languages') #5 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Themes.php(321): Grav\Common\Themes->loadLanguages(Object(Grav\Common\Config\Config)) #6 /home/xxxxxxxx/public_html/themes/gateway/user/plugins/admin/classes/plugin/Themes.php(17): Grav\Common\Themes->configure() #7 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Processors/ThemesProcessor.php(35): Grav\Plugin\Admin\Themes->init() #8 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #9 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #10 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #11 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #12 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #13 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #14 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #15 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile(Object(Closure)) #16 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #17 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /home/xxxxxxxx/public_html/themes/gateway/system/src/Grav/Common/Grav.php(303): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #19 /home/xxxxxxxx/public_html/themes/gateway/index.php(58): Grav\Common\Grav->process() #20 {main} [] []`

**Comment by ghost** [comment]
Couldn't replicate this. It worked correctly when I re-installed.
